language: racket

env:
 - RACKET_VERSION=HEAD

before_install:
 - git clone https://github.com/greghendershott/travis-racket.git
 - cat travis-racket/install-racket.sh | bash
 - export PATH="${RACKET_DIR}/bin:${PATH}"

install:

before_script:

script:
 - raco link .
 - raco test -l data/ralist/run-tests
